version: '3'

vars:
  SITE_DOCKER_FLAGS: >-
    -v ./www:/docs
    -v ./LICENSE:/docs/docs/LICENSE
    -v ./SECURITY.md:/docs/docs/security.md
    -v ./CHANGELOG.md:/docs/docs/changelog.md
    -v ./CODE-OF-CONDUCT.md:/docs/docs/code-of-conduct.md
    -v ./CONTRIBUTING.md:/docs/docs/contributing.md

tasks:
  build:webui:
    desc: Build webui assets
    dir: webui
    cmds:
      - npm ci
      - npm run generate

  build:backend:
    desc: Build backend binary
    env:
      CGO_ENABLED: '1'
      GO111MODULE: 'on'
    cmds:
      - go build -ldflags='-s -w -X "github.com/fluxionwatt/manager/version.Version={{.VERSION}}" -X "github.com/fluxionwatt/manager/version.BUILDTIME={{.BUILD_TIME}}" -X "github.com/fluxionwatt/manager/version.CommitSHA={{.GIT_COMMIT}}"' -o manager .
    vars:
      BUILD_TIME:
        sh: date -u +"%Y-%m-%dT%H:%M:%SZ"
      GIT_COMMIT:
        sh: git log -n 1 --format=%h
      VERSION:
        sh: git describe --tags --abbrev=0 --match=v* | cut -c 2-

  build:
    desc: Build both webui and backend
    cmds:
      - task: build:webui
      - task: build:backend

  pub:
    desc: Publish site to GitHub Pages
    cmds:
      - echo
